In [1]:
import pandas as pd

In [6]:
train_df = pd.read_csv('../../data/train_sessions.csv')

In [7]:
test_df = pd.read_csv('../../data/test_sessions.csv')

In [8]:
train_df.shape

(253561, 22)

In [9]:
train_df.head()

session_id  site1                time1  site2                time2  \
0           1    718  2014-02-20 10:02:45    NaN                  NaN   
1           2    890  2014-02-22 11:19:50  941.0  2014-02-22 11:19:50   
2           3  14769  2013-12-16 16:40:17   39.0  2013-12-16 16:40:18   
3           4    782  2014-03-28 10:52:12  782.0  2014-03-28 10:52:42   
4           5     22  2014-02-28 10:53:05  177.0  2014-02-28 10:55:22   

     site3                time3    site4                time4  site5   ...    \
0      NaN                  NaN      NaN                  NaN    NaN   ...     
1   3847.0  2014-02-22 11:19:51    941.0  2014-02-22 11:19:51  942.0   ...     
2  14768.0  2013-12-16 16:40:19  14769.0  2013-12-16 16:40:19   37.0   ...     
3    782.0  2014-03-28 10:53:12    782.0  2014-03-28 10:53:42  782.0   ...     
4    175.0  2014-02-28 10:55:22    178.0  2014-02-28 10:55:23  177.0   ...     

                 time6    site7                time7    site8  \
0                  NaN      NaN                  NaN      NaN   
1  2014-02-22 11:19:51   3847.0  2014-02-22 11:19:52   3846.0   
2  2013-12-16 16:40:19  14768.0  2013-12-16 16:40:20  14768.0   
3  2014-03-28 10:54:42    782.0  2014-03-28 10:55:12    782.0   
4  2014-02-28 10:55:59    175.0  2014-02-28 10:55:59    177.0   

                 time8    site9                time9   site10  \
0                  NaN      NaN                  NaN      NaN   
1  2014-02-22 11:19:52   1516.0  2014-02-22 11:20:15   1518.0   
2  2013-12-16 16:40:21  14768.0  2013-12-16 16:40:22  14768.0   
3  2014-03-28 10:55:42    782.0  2014-03-28 10:56:12    782.0   
4  2014-02-28 10:55:59    177.0  2014-02-28 10:57:06    178.0   

                time10  target  
0                  NaN       0  
1  2014-02-22 11:20:16       0  
2  2013-12-16 16:40:24       0  
3  2014-03-28 10:56:42       0  
4  2014-02-28 10:57:11       0  

[5 rows x 22 columns]

In [10]:
features = ['site%d' % i for i in range(1, 11)]

In [11]:
train_df[features].head()

site1  site2    site3    site4  site5   site6    site7    site8    site9  \
0    718    NaN      NaN      NaN    NaN     NaN      NaN      NaN      NaN   
1    890  941.0   3847.0    941.0  942.0  3846.0   3847.0   3846.0   1516.0   
2  14769   39.0  14768.0  14769.0   37.0    39.0  14768.0  14768.0  14768.0   
3    782  782.0    782.0    782.0  782.0   782.0    782.0    782.0    782.0   
4     22  177.0    175.0    178.0  177.0   178.0    175.0    177.0    177.0   

    site10  
0      NaN  
1   1518.0  
2  14768.0  
3    782.0  
4    178.0

In [46]:
y_train = train_df['target']

In [47]:
y_train.mean()

0.00905896411514389

In [18]:
import pickle
from collections import Counter

In [14]:
with open('../../data/site_dic.pkl', 'rb') as inp_file:
    site_dict = pickle.load(inp_file)

In [29]:
site_freqs = Counter(train_df[features].fillna(0).astype('int').values.ravel()).most_common(10)

In [37]:
inv_site_dict = {v: k for (k, v) in site_dict.items()}

In [35]:
site_freqs

[(21, 123776),
 (0, 122730),
 (23, 87619),
 (782, 77055),
 (22, 58258),
 (29, 54094),
 (167, 46405),
 (780, 43841),
 (778, 38194),
 (52, 36085)]

In [38]:
inv_site_dict

{25075: 'www.abmecatronique.com',
 13997: 'groups.live.com',
 42436: 'majeureliguefootball.wordpress.com',
 30911: 'cdt46.media.tourinsoft.eu',
 8104: 'www.hdwallpapers.eu',
 37491: 'img378.imageshack.us',
 5462: 'ecologie.nature.free.fr',
 35425: 'www.ibcn.intec.ugent.be',
 30151: 'kissanime.com',
 38268: 'www.carolineconduiteformation.com',
 43641: 'images.mystockphoto.com',
 36959: 'journalph.csphares.qc.ca',
 40935: 'www.uqo.ca',
 12346: 'd8d94e0wul1nb.cloudfront.net',
 31023: 'openapi.elong.com',
 31114: 'flamenco-o.blogspot.com',
 28165: 'www.pages-annuaire.net',
 31877: 'smart2000.pagesperso-orange.fr',
 31070: 'fast.forbes.com',
 12938: 'i1-js-14-3-01-10077-536503633-i.init.cedexis-radar.net',
 42002: 'i1-js-14-3-01-11074-716595896-i.init.cedexis-radar.net',
 5671: 'www.pacajob.com',
 32074: 'mathaa.epfl.ch',
 7104: 'cbv.sfr.bench.cedexis.com',
 1939: 'fbcdn-sphotos-b-a.akamaihd.net',
 6708: 'www.mystere-tv.com',
 43589: 'www.mon-ip.fr',
 45241: 'www.aqua-passion.com',
 16195: 

In [41]:
for i, _ in site_freqs:
    print(inv_site_dict.get(i))

www.google.fr
None
www.google.com
annotathon.org
apis.google.com
www.facebook.com
www.bing.com
blast.ncbi.nlm.nih.gov
www.ncbi.nlm.nih.gov
clients1.google.com


In [50]:
import numpy as np
from scipy.sparse import csr_matrix

In [53]:
a = np.zeros([3, 10])
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
a[0, 6] = 5
a[0, 8] = 1
a[1, 1] = 3
a[2, 3] = 2

In [55]:
a

array([[0., 0., 0., 0., 0., 0., 5., 0., 1., 0.],
       [0., 3., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 0., 0., 0., 0.]])

In [56]:
a_sparse = csr_matrix(a)

In [57]:
a_sparse

<3x10 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [58]:
a_sparse.nonzero()

(array([0, 0, 1, 2], dtype=int32), array([6, 8, 1, 3], dtype=int32))

In [59]:
a_sparse.data

array([5., 1., 3., 2.])

In [60]:
a

array([[0., 0., 0., 0., 0., 0., 5., 0., 1., 0.],
       [0., 3., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 0., 0., 0., 0.]])

In [61]:
train_df[features].head()

site1  site2    site3    site4  site5   site6    site7    site8    site9  \
0    718    NaN      NaN      NaN    NaN     NaN      NaN      NaN      NaN   
1    890  941.0   3847.0    941.0  942.0  3846.0   3847.0   3846.0   1516.0   
2  14769   39.0  14768.0  14769.0   37.0    39.0  14768.0  14768.0  14768.0   
3    782  782.0    782.0    782.0  782.0   782.0    782.0    782.0    782.0   
4     22  177.0    175.0    178.0  177.0   178.0    175.0    177.0    177.0   

    site10  
0      NaN  
1   1518.0  
2  14768.0  
3    782.0  
4    178.0

In [62]:
from sklearn.feature_extraction.text import CountVectorizer

In [74]:
cv = CountVectorizer()
texts = ['hello world', 
         "hello, I'm Yury", 
         "who is Yury, Yury is a guy"]
cv.fit(texts)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [75]:
cv.vocabulary_

{'guy': 0, 'hello': 1, 'is': 2, 'who': 3, 'world': 4, 'yury': 5}

In [76]:
sparse_repr = cv.transform(texts)

In [77]:
sparse_repr

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [78]:
sparse_repr.nonzero(), sparse_repr.data

((array([0, 0, 1, 1, 2, 2, 2, 2], dtype=int32),
  array([1, 4, 1, 5, 0, 2, 3, 5], dtype=int32)),
 array([1, 1, 1, 1, 1, 2, 1, 2]))

In [82]:
train_df[features].fillna(0).astype('int').to_csv('../../data/train_sessions_space_delim.txt',
                                       sep=' ', index=None, header=None)

In [84]:
test_df[features].fillna(0).astype('int').to_csv('../../data/test_sessions_space_delim.txt',
                                       sep=' ', index=None, header=None)

In [83]:
!head ../../data/train_sessions_space_delim.txt

718 0 0 0 0 0 0 0 0 0
890 941 3847 941 942 3846 3847 3846 1516 1518
14769 39 14768 14769 37 39 14768 14768 14768 14768
782 782 782 782 782 782 782 782 782 782
22 177 175 178 177 178 175 177 177 178
570 21 570 21 21 0 0 0 0 0
803 23 5956 17513 37 21 803 17514 17514 17514
22 21 29 5041 14422 23 21 5041 14421 14421
668 940 942 941 941 942 940 23 21 22
3700 229 570 21 229 21 21 21 2336 2044


In [86]:
%%time
cv = CountVectorizer()
with open('../../data/train_sessions_space_delim.txt') as inp_file:
    X_train_sparse = cv.fit_transform(inp_file)

CPU times: user 2.68 s, sys: 65.5 ms, total: 2.74 s
Wall time: 2.74 s


In [89]:
X_train_sparse

<253561x41592 sparse matrix of type '<class 'numpy.int64'>'
	with 1403272 stored elements in Compressed Sparse Row format>

In [90]:
with open('../../data/test_sessions_space_delim.txt') as inp_file:
    X_test_sparse = cv.transform(inp_file)

In [91]:
X_test_sparse

<82797x41592 sparse matrix of type '<class 'numpy.int64'>'
	with 414906 stored elements in Compressed Sparse Row format>

In [94]:
X_train_sparse[0, :].nonzero(), X_train_sparse[0, :].data

((array([0], dtype=int32), array([38462], dtype=int32)), array([1]))

In [96]:
from sklearn.linear_model import LogisticRegression

In [98]:
logit = LogisticRegression(random_state=17)

In [99]:
%%time
logit.fit(X_train_sparse, y_train)

CPU times: user 4.06 s, sys: 44.1 ms, total: 4.1 s
Wall time: 4.11 s


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=17, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [100]:
logit.coef_

array([[ 5.63456058e-01, -4.60401830e-04, -1.64367711e-02, ...,
        -4.44552266e-02, -5.49560680e-04, -5.30144564e-02]])

In [118]:
from sklearn.metrics import accuracy_score, roc_auc_score, recall_score, confusion_matrix

In [102]:
from sklearn.model_selection import train_test_split

In [105]:
X_train_part, X_valid, y_train_part, y_valid = train_test_split(X_train_sparse, y_train,
                                                               test_size=0.3, shuffle=True,
                                                               random_state=17,
                                                               stratify=y_train)

In [106]:
%%time
logit.fit(X_train_part, y_train_part)

CPU times: user 2.87 s, sys: 22.7 ms, total: 2.9 s
Wall time: 2.9 s


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=17, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [107]:
accuracy_score(y_valid, logit.predict(X_valid))

0.9919678186909253

In [109]:
1 - y_valid.mean()

0.9909424338429583

In [113]:
roc_auc_score(y_valid, logit.predict_proba(X_valid)[:, 1])

0.9616043974197881

In [115]:
recall_score(y_valid, logit.predict(X_valid))

0.1741654571843251

In [117]:
y_valid.sum(), y_valid.shape[0]

(689, 76069)

In [119]:
confusion_matrix(y_valid, logit.predict(X_valid))

array([[75338,    42],
       [  569,   120]])

In [120]:
logit.fit(X_train_sparse, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=17, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [121]:
logit_test_pred = logit.predict_proba(X_test_sparse)[:, 1]

In [122]:
logit_test_pred.shape

(82797,)

In [125]:
sample_subm = pd.read_csv('../../data/alice_sample_submission.csv', index_col='session_id')

In [126]:
sample_subm.head()

target
session_id          
1           0.948255
2           0.682483
3           0.502855
4           0.345556
5           0.889428

In [127]:
sample_subm['target'] = logit_test_pred

In [128]:
sample_subm.head()

target
session_id              
1           2.429866e-03
2           5.106001e-09
3           1.884191e-08
4           3.001811e-08
5           3.344001e-05

In [129]:
sample_subm.to_csv('alice_first_submission.csv')

In [130]:
!head alice_first_submission.csv

session_id,target
1,0.0024298658360507285
2,5.106001352403285e-09
3,1.884191201405876e-08
4,3.001811358798685e-08
5,3.344001301837542e-05
6,0.00029145378368981807
7,0.0008029988079506223
8,0.0001664563047680165
9,0.0009129090741140757
